### ISSUE TITLE
Tooltip data is disappearing

### ISSUE THREAD

**Issue by eTzmNcbkrng** [project-classic/ClassicCodex#1]
The first time you mouseover a mob, the tooltip correctly displays relevant quest requirements.  
If you move your mouse away then back onto the mob, only the default tooltip displays.  
It seems that mousing over a Unit Frame will reset this behaviour.
Tested with no other addons running and issue persists.
See these two screenshots taken immediately after one another.

![WoWScrnShot_080919_220243](https://user-images.githubusercontent.com/26512802/62771788-20673f00-baf2-11e9-9ed0-7cb47c88f5f5.jpg)
![WoWScrnShot_080919_220246](https://user-images.githubusercontent.com/26512802/62771789-20673f00-baf2-11e9-98f4-c9800ff3254c.jpg)

**Comment by pgarneau** [comment]
Yeah I noticed that bug also while testing it myself. I know that letting the tooltip completely disappear and then mousing over again fixes the behavior, but I don't know why I have to let it disappear. Hovering over the nameplate probably just generates a fresh tooltip object within the game.

**Comment by pgarneau** [comment]
Fixed
