### ISSUE TITLE
Ability to search for items / nodes / mobs

### ISSUE THREAD

**Issue by PugzM** [project-classic/ClassicCodex#11]
Feature request / question.

In pfQuest you could search for items / nodes and they would be added to the map by right clicking them. Will this functionality eventually be imported?
Aside from that - VERY nice work and ty so much for this port. One of the main addons I was hoping to see get ported.

**Comment by pgarneau** [comment]
You can search for items/nodes/mobs by using `/codex` commands. Map will
open up with black markers to show locations

**Comment by PugzM** [comment]
Will it be possible to alter the color of markers - e.g. you could set different herbs to different colors for example.
Will there be plans to implement an addon window like pfquest had?

**Comment by pgarneau** [comment]
Both of those are done in version 1.2.0 and 1.2.1

**Comment by PugzM** [comment]
Awesome work. You are a god.
