### ISSUE TITLE
Bug on beta, level 40 preset

### ISSUE THREAD

**Issue by MalikenGD** [project-classic/ClassicCodex#12]
Here are some various images:

https://i.imgur.com/jEqpqxK.jpg

https://i.imgur.com/IyZE1Vs.jpg (count goes up by one every quarter second or so)

**FIRST ERROR REPEATING:** 

Message: ...icCodex\lib\HereBeDragons\HereBeDragons-Pins-2.0.lua:689: HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers
Time: Wed Aug 14 03:18:19 2019
Count: 104
Stack: ...icCodex\lib\HereBeDragons\HereBeDragons-Pins-2.0.lua:689: HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers
[C]: in function `error'
...icCodex\lib\HereBeDragons\HereBeDragons-Pins-2.0.lua:689: in function `AddWorldMapIconMap'
Interface\AddOns\ClassicCodex\map.lua:529: in function `UpdateNodes'
Interface\AddOns\ClassicCodex\quest.lua:158: in function <Interface\AddOns\ClassicCodex\quest.lua:146>

Locals: (*temporary) = "HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers"

**SECOND ERROR REPEATING:** 

Message: ...icCodex\lib\HereBeDragons\HereBeDragons-Pins-2.0.lua:689: HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers
Time: Wed Aug 14 03:17:58 2019
Count: 1
Stack: ...icCodex\lib\HereBeDragons\HereBeDragons-Pins-2.0.lua:689: HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers
[C]: in function `error'
...icCodex\lib\HereBeDragons\HereBeDragons-Pins-2.0.lua:689: in function `AddWorldMapIconMap'
Interface\AddOns\ClassicCodex\map.lua:529: in function `UpdateNodes'
Interface\AddOns\ClassicCodex\map.lua:542: in function <Interface\AddOns\ClassicCodex\map.lua:541>

Locals: (*temporary) = "HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers"

**Comment by pgarneau** [comment]
Are you using the latest version? Made the same character on beta and it
works for me

That bug was fixed in 1.0.1 if i recall
