### ISSUE TITLE
Map combobox position.

### ISSUE THREAD

**Issue by malkaviano** [project-classic/ClassicCodex#17]
Having a little problem with the map combo box on the right, it's on top of my coords added by another addon.

Would you shift it to the left or add an option to do so?

**Comment by Havenloft** [comment]
Yes!

The dropdown menu on the world map asking which markers to display.

I would love to have an option in the interface to be able to hide/show that menu or perhaps the option to switch it to the left side of the map. It unfortunately interferes with my cursor coordinates as well in it's current state and I don't see any reason to need access to that dropdown except for on specific circumstances.

**Comment by SwimmingTiger** [comment]
We can adding a similar drop-down menu in the settings interface and allowing the drop-down menu on the world map to be hidden.
