### ISSUE TITLE
Addon Compatibility Issues

### ISSUE THREAD

**Issue by reaktorblue** [project-classic/ClassicCodex#18]
I'm using two addons that seem to have some compatibility issues with Classic Codex.

**Titan Panel**
There is an issue with the combo box placement for selecting quests on the world map. Titan Panel enables player coordinates and the combo box placement is on top of the coordinates. Would it be possible to adjust the placement of the combo box?

**Quest Log Extended**
There is an issue with the show, hide, and reset options of Classic Codex on the quest journal. Quest Log Extended enables a longer, easier sorted list of quests however, the quest details does not contain the Classic Codex options. Would it be possible to have the options with Quest Log Extended as well?

**Comment by Maycke25** [comment]
hi, when i enable the zygor addon it no longer shows the points where the mission objectives are on the big map (by pressing the "M")
sorry my google english, great addon.

**Comment by pgarneau** [comment]
Integration with other addons is really hard.

Codex uses the default Map and the default quest log to "attach itself". Once other addons start replacing those defaults with custom ones, codex needs to know those custom ones to attach to them.

**Comment by Albirew** [comment]
I'd also like to add that most addons uses the LibDBIcon library in order to make minimap buttons customizable/integrable/usable by other addons (like sexymap, titan panel and some revamped theme addons).
