### ISSUE TITLE
Ability to hide spawn nodes on map

### ISSUE THREAD

**Issue by MrFox42** [project-classic/ClassicCodex#19]
Feature request. 

I would like to hide spawn nodes on the map, while still showing quest icons.

**Comment by eTzmNcbkrng** [comment]
Top right of the map, select "Manual Selection" in the drop-down menu.

**Comment by MrFox42** [comment]
Ah, I thought that would hide everything unless I select them manually (including quest icons), but looks like it does what I wanted. Thanks!
