### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Finrodi** [project-classic/ClassicCodex#2]
```
Message: ...icCodex\lib\HereBeDragons\HereBeDragons-Pins-2.0.lua:689: HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers
Time: Fri Aug  9 15:10:37 2019
Count: 1
Stack: ...icCodex\lib\HereBeDragons\HereBeDragons-Pins-2.0.lua:689: HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers
[C]: in function `error'
...icCodex\lib\HereBeDragons\HereBeDragons-Pins-2.0.lua:689: in function `AddWorldMapIconMap'
Interface\AddOns\ClassicCodex\map.lua:529: in function `UpdateNodes'
Interface\AddOns\ClassicCodex\quest.lua:168: in function <Interface\AddOns\ClassicCodex\quest.lua:146>

Locals: (*temporary) = "HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers"

```

**Comment by Finrodi** [comment]
another one 

```
Message: ...icCodex\lib\HereBeDragons\HereBeDragons-Pins-2.0.lua:689: HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers
Time: Fri Aug  9 15:21:08 2019
Count: 1
Stack: ...icCodex\lib\HereBeDragons\HereBeDragons-Pins-2.0.lua:689: HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers
[C]: in function `error'
...icCodex\lib\HereBeDragons\HereBeDragons-Pins-2.0.lua:689: in function `AddWorldMapIconMap'
Interface\AddOns\ClassicCodex\map.lua:529: in function `UpdateNodes'
Interface\AddOns\ClassicCodex\map.lua:542: in function <Interface\AddOns\ClassicCodex\map.lua:541>

Locals: (*temporary) = "HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'uiMapID', 'x' and 'y' must be numbers"

```

**Comment by pgarneau** [comment]
Could you try and indentify it's happening on what mob / NPC / quest? Maybe the data is wrong somewhere

**Comment by Finrodi** [comment]
Not sure but I was able to click on the map to remove a quest (Cluck!) because its spamming everywhere and now I cant remove anymore. Otherwise no clue, i get the error when logging in.

**Comment by pgarneau** [comment]
Yeah quests like Cluck! with multiple pickup locations will clutter your map.. That's why I initially only displayed the icons on the map your player was currently in.

I don't know how viable this is for you, but could you try deleting quests from your questlog until the problem stops and give me the quest that causes the issue? If not, what level are you atm? If you make a fresh character, does the error persist or is it only on that 1 character

**Comment by Finrodi** [comment]
Level 1 char doesnt have the rror btw.

**Comment by pgarneau** [comment]
Could you try running `/codex reset` ingame on your char with the error? Curious to see if it fixes your problem.

**Comment by Finrodi** [comment]
Does not fix the problems, errors reappear after I do that.
One of them is actually
```
Message: (null)
Time: Fri Aug  9 16:37:03 2019
Count: 6
```

As well 🗡

**Comment by pgarneau** [comment]
Could you go here in the code https://github.com/project-classic/ClassicCodex/blob/master/map.lua#L527 and add 3 lines:
```
print(coords)
print(x)
print(y)
```
It will write the values in your chat ingame. Could you give me those values for the one that's breaking?

**Comment by pgarneau** [comment]
And if you're feeling fancy, could you also add:
```
for title, meta in pairs(node) do
        print(title)
end
```

This will be extra spammy in your chat, but itll tell me what quest is breaking it

**Comment by Finrodi** [comment]
had to leave, not sure if i can make it before servers go down :(

**Comment by stampis** [comment]
The issue starts when you ding level 20, guessing its due to some quests becoming avaliable then.
Seems to be cuz of faulty zone<>mapid?

Here are the last returned coords and Quest:.
```
74.9|44.1
0.749
0.441
A Fine Mess
```

**Comment by Finrodi** [comment]
My char was level 9 with those error messages btw.

**Comment by pgarneau** [comment]
@Finrodi Horde or ally?


@stampis Any chance you can give me the other returned coords and quest? Im trying to see if its an error in the database (coords / x / y) or an error with the mapID. I inverted the list by hand right before releasing so I might have added a bug

**Comment by stampis** [comment]
My first test was on Human (Paladin)...
The quest that throws the error is located in Gnomeregan..
Error occured when characted dinged 20 (quest level?)

Second test i did was on Undead (Warrior)...
The quest that throws the error is located in Blackfathom Villainy..
Error occured when characted dinged 17 (quest level?)

Coords:  20.1|52.3
X:  0.201
Y:  0.523

**Comment by pgarneau** [comment]
Ok That's probably my problem @stampis I have basic zones, but not the instanced ones. Shagu didn't have that feature so I had to make it from scratch and there's a bug. Ill fix it asap, but I'm going away for the weekend so I can't do it till sunday.

Any chance you guys make a PR updating `CodexMap.zones` inside `map.lua` with the missing ids? Maybe there's a WoW API call to translate the mapId to worldMapId

**Comment by stampis** [comment]
yeah the "worldMapId" returns "nil" for those..

So with:
```
for title, meta in pairs(node) do
        print(title)
end

print(worldMapId)
```

I got something like this:
```
Avenge My Village
1442
Trouble in the Deeps
Elemental War
1442
Blackfathom Villainy
nil
```

**Comment by pgarneau** [comment]
Actually the real ID we're trying to get from the WoW API is `uiMapID`

**Comment by pgarneau** [comment]
I might just push a quick fix for now and check for null. Itll at least prevent lua errors for now

**Comment by pgarneau** [comment]
@stampis Have you noticed any performance issues? I heard from buddies that they had some performance issues in loch modan

**Comment by pgarneau** [comment]
Temporary fix pushed, please download the latest version and let me know if the issue is fixed

**Comment by stampis** [comment]
The temp fix solved the lua errors.
And i did not notice any performance issues at all while in Thelsamar - Loch Modan

**Comment by Finrodi** [comment]
`Message: (null)
Time: Sat Aug 10 00:59:15 2019
Count: 6`

Lua error is gone, correct however this one still exists... obviously hard to tell what the problem is^^
