### ISSUE TITLE
Doesn't work with clients in Spanish? America

### ISSUE THREAD

**Issue by icomputo** [project-classic/ClassicCodex#21]
Doesn't work with clients in Spanish? America
Missions in progress are not shown on the map.

**Comment by pgarneau** [comment]
Are you using an "esES" client?

If so, it should technically work since I have reports it works on french and german clients.
Need more details

**Comment by icomputo** [comment]
Español(AL)

**Comment by icomputo** [comment]
this is the solution to the problem
https://github.com/project-classic/ClassicCodex/pull/24

**Comment by SwimmingTiger** [comment]
The previous code uses the title of the quest provided by Blizzard to match the title in the database, and there will be problems when the two are inconsistent.

My Pull Request https://github.com/project-classic/ClassicCodex/pull/33 should fix this problem, you can try it again and see if everything OK.
