### ISSUE TITLE
Show/Hide/Reset buttons disappear when using QuestLogEX

### ISSUE THREAD

**Issue by alecjpav** [project-classic/ClassicCodex#22]
Hello, thanks for this addon! Is there a way to make this compatible with QuestLogEX (spiritual successor to EQL3)? The buttons ClassicCodex integrates into the quest log are missing with that addon enabled.

The developer of that addon told me that this is something that you would have to fix on your end.

Thank you very much!

QuestLogEX disabled:
![MFaLaLU](https://user-images.githubusercontent.com/28431403/64070551-c3a20480-cc17-11e9-955a-454275610f75.jpg)

QuestLogEX enabled:
![RgM7abA](https://user-images.githubusercontent.com/28431403/64070552-c7358b80-cc17-11e9-981a-ad4480d1906c.jpg)

**Comment by SwimmingTiger** [comment]
I added Show/Hide/Reset buttons to QuestLogEX by modifying QuestLogEX itself. Some part of UI language has been modified to Chinese, you can change it back as needed.

![双栏任务日志](https://user-images.githubusercontent.com/4986069/64647434-97725900-d44b-11e9-9432-7099d9b64f51.png)

[ClassicCodex+QuestLogEX+BlizzMove.zip](https://github.com/project-classic/ClassicCodex/files/3597553/%2B.%2B.zip)

**Comment by alecjpav** [comment]
> I added Show/Hide/Reset buttons to QuestLogEX by modifying both ClassicCodex (add show/hide function) and QuestLogEX (add buttons to XML). Some part of UI language has been modified to Chinese, you can change it back as needed.
> 
> ![双栏任务日志](https://user-images.githubusercontent.com/4986069/64647434-97725900-d44b-11e9-9432-7099d9b64f51.png)
> 
> [ClassicCodex+QuestLogEX+BlizzMove.zip](https://github.com/project-classic/ClassicCodex/files/3597553/ClassicCodex%2BQuestLogEX%2BBlizzMove.zip)
> 
> There are my commits:
> [SwimmingTiger/WowBigfootClassic@d5f6213](https://github.com/SwimmingTiger/WowBigfootClassic/commit/d5f6213d80bc34ec321371f3c957384ace50ae3d)
> [SwimmingTiger/WowBigfootClassic@5a64796](https://github.com/SwimmingTiger/WowBigfootClassic/commit/5a647967ca0e614541b9e984bdcd4dfd65e56dac)

非常感谢! I really like how you put the buttons in the frame.

**Comment by SwimmingTiger** [comment]
@alecjpav It is:
`Please drag the left part of the title bar`

Because the right side of the title bar cannot be dragged, some people may mistakenly think that the entire UI cannot be dragged.

The combination of the XML frames determines that drag support cannot be easily added to the right part via BlizzMove (it is actually another frame).

**Comment by alecjpav** [comment]
@SwimmingTiger Am I going to have to add these changes every time the addon is updated? Because the lines you added are missing in the new update's code, so I guess that wasn't part of what was merged. But despite that it seems the buttons still display and function as intended without that code you added, and I'm not sure why.

**Comment by olepg** [comment]
I recommend using Wide Quest Log: https://gitlab.com/bloodline_/widequestlog
It's the same function, but also works with Classic Codex.

**Comment by alecjpav** [comment]
> I recommend using Wide Quest Log: https://gitlab.com/bloodline_/widequestlog
> It's the same function, but also works with Classic Codex.

Thanks for the heads up! Out of curiosity and to help those who run into the same dilemma I decided to test 4 quest log addons to see how they work with ClassicCodex, including this one.

1. QuestLogEx (Didn't work with ClassicCodex originally, but seems to now after the latest update. I deleted my old addon folder and saved variables just to make sure the changes we made weren't being carried over. Can't find the lines of code in that changed this in the new update either. I'm not sure what's going on here but I have to assume these changes were added in the update through different lines of code even though they weren't mentioned in the changelog):
![1 QuestLogEx](https://user-images.githubusercontent.com/28431403/65463113-0cf70580-de0c-11e9-8e04-7270960345a0.jpg)

2. WideQuestLog + WideQuestLogLevels (works with ClassicCodex)
![2 Wide Quest Log](https://user-images.githubusercontent.com/28431403/65463145-20a26c00-de0c-11e9-9e62-4576107e5389.jpg)

3. Leatrix Plus "Enchance Quest Log" option (works with ClassicCodex)
![3 Leatrix](https://user-images.githubusercontent.com/28431403/65463449-94dd0f80-de0c-11e9-9aae-046ec67fdbef.jpg)

4.  QuestGuru (doesn't work with ClassicCodex)
![4 QuestGuru](https://user-images.githubusercontent.com/28431403/65463488-aaead000-de0c-11e9-8e59-0ba2f73fd490.jpg)

Interesting that WideQuestLog and Leatrix Plus are almost exactly the same.
