### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Edwin18** [project-classic/ClassicCodex#25]
251x ClassicCodex\quest.lua:216: bad argument #1 to 'strfind' (string expected, got nil)
[C]: in function `strfind'
ClassicCodex\quest.lua:216: in function `UpdateQuestLog'
ClassicCodex\quest.lua:134: in function <ClassicCodex\quest.lua:130>

Locals:
(*temporary) = nil
(*temporary) = "(.*):%s*([%d]+)%s*/%s*([%d]+)"
(*temporary) = "string expected, got nil"

![image](https://user-images.githubusercontent.com/8036656/64159946-bcf7d500-ce43-11e9-86af-616d80246bc3.png)

**Comment by SwimmingTiger** [comment]
It should be fixed in this commit:
https://github.com/project-classic/ClassicCodex/commit/4142bb5d03a733a75578592034c0af09efe4269a
