### ISSUE TITLE
Drastic UI slowdown on certain Quests

### ISSUE THREAD

**Issue by kg6ebj** [project-classic/ClassicCodex#26]
WOW hangs for 1-2 seconds on certain quests. an example quest would be the Alliance druid poison quest where you map every possible node of earth root on the entire world, not just the zone we are in (Darkshore) with ClassicCodex disabled or after that quest is complete the slowdown/UI hang is resolved.

**Comment by pgarneau** [comment]
Fixed in upcoming release
