### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Edwin18** [project-classic/ClassicCodex#28]
1x ClassicCodex\map.lua:87: Attempt to access forbidden object from code tainted by an AddOn
[C]: in function `GetName'
ClassicCodex\map.lua:87: in function `showTooltip'
ClassicCodex\map.lua:110: in function <ClassicCodex\map.lua:108>

Locals:
(*temporary) = SecureTransferDialog {
 0 = <userdata>
 ticker = <table> {
 }
 Button1 = <unnamed> {
 }
 MoneyLabel = <unnamed> {
 }
 CautionIcon = <unnamed> {
 }
 Text = <unnamed> {
 }
 Button2 = <unnamed> {
 }
 acceptTimeLeft = 0
}

![image](https://user-images.githubusercontent.com/8036656/64275593-9a9eae00-cf4e-11e9-887a-456038f49bd9.png)

**Comment by dabing1986** [comment]
same error occurs to me as well whenever to access to specific area

**Comment by pgarneau** [comment]
Fix should be coming with new release
