### ISSUE TITLE
394: Attempt to access forbidden object from code tainted by an AddOn

### ISSUE THREAD

**Issue by TyThompson** [project-classic/ClassicCodex#42]
Message: Interface\AddOns\ClassicCodex\quest.lua:394: Attempt to access forbidden object from code tainted by an AddOn
Time: Sun Sep 29 22:56:02 2019
Count: 18
Stack: Interface\AddOns\ClassicCodex\quest.lua:394: Attempt to access forbidden object from code tainted by an AddOn
[C]: in function `GetName'
Interface\AddOns\ClassicCodex\quest.lua:394: in function `CheckNamePlate'
Interface\AddOns\ClassicCodex\quest.lua:124: in function <Interface\AddOns\ClassicCodex\quest.lua:26>

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}

**Comment by TyThompson** [comment]
This function is causing it

```
function --[ CodexQuest:CheckNamePlate() ]--
    if IsInInstance() then return end
    local something = WorldFrame:GetNumChildren()
    local index = 1
    local plateList = {}
    for index = 1, something do
        local frame = select(index, WorldFrame:GetChildren())
        if frame and frame:GetName() and frame:GetName():find("NamePlate%d") and not frame.skinned then
            frame.skinned = 1
            frame.icon = CreateFrame("Frame", nil, frame)
            frame.icon:SetFrameStrata("HIGH")
            frame.icon:SetWidth(25)
            frame.icon:SetHeight(25)

            local texture = frame.icon:CreateTexture(nil, "HIGH")
            texture:SetTexture("Interface\\Addons\\ClassicCodex\\img\\pickup.tga")
            texture:SetAllPoints(frame.icon)
            frame.icon.texture = texture
            frame.icon:SetPoint("BOTTOM", frame, "TOP", 0, 0)
        end
        if frame["UnitFrame"] and frame["UnitFrame"]["displayedUnit"] then
            local name = frame["UnitFrame"]["name"]:GetText()
            frame.icon:Hide()
            for title in pairs(CodexQuest.questLog) do
                if name and CodexMap.tooltips[name] and CodexMap.tooltips[name][title] then
                    frame.icon:Show()
                    break
                else
                    frame.icon:Hide()
                end
            end
        end
    end
end
```

**Comment by pgarneau** [comment]
Are you running on master branch and/or the latest version?

The code you linked is currently outdated. 

There's another issue atm in that code, but shouldn't be causing any errors anymore

**Comment by SwimmingTiger** [comment]
I think this Pull Request can fix the problem: https://github.com/project-classic/ClassicCodex/pull/39
If you want a fix archive, you can download it from here:
https://github.com/LiangYuxuan/ClassicCodex/archive/patch-1.zip
