### ISSUE TITLE
Random Lua Error

### ISSUE THREAD

**Issue by sirFAYDE** [project-classic/ClassicCodex#46]
![image](https://user-images.githubusercontent.com/37656345/66273269-1ad07000-e87b-11e9-928f-65778e75cd9e.png)
It happens randomly when you run / fly around some mobs (it does not appear when the "Nameplate Quest Icon" is disabled). Appears even when there are no quests for mobs.

**Comment by pgarneau** [comment]
Are you on latest version?

**Comment by sirFAYDE** [comment]
Yes

**Comment by sirFAYDE** [comment]
![image](https://user-images.githubusercontent.com/37656345/66274490-15c5ed80-e888-11e9-8b32-7ede3e9aed2a.png)
another error, but I see this for the first time and it appeared when I was in Stormwind

**Comment by SwimmingTiger** [comment]
Version 1.2.2 does not include a valid fix for nameplate access. 

These two commits need to be included in the code to completely resolve the issue.
https://github.com/project-classic/ClassicCodex/pull/36
https://github.com/SwimmingTiger/ClassicCodex/commit/bb4897ebb3f032bc05908b50d15b448ed4a299ea

You can try the following pre-releases. It has the code to prevent nameplate access errors.
https://github.com/SwimmingTiger/ClassicCodex/releases/tag/1.3-staging
