### ISSUE TITLE
[Suggestion] Show quest markers on world map

### ISSUE THREAD

**Issue by jukx** [project-classic/ClassicCodex#47]
Hi, I like many of the features of this addon, but the one thing Questie has, that ClassicCodex lacks is the display of quest markers on the world map. With this, you can check on one screen if there are any new quests that popped up or where you have to do/turn in quests.

Until this is implemented, Questie is much more convenient, unfortunately.

**Comment by jukx** [comment]
Hah, I looked into the code and actually, this is possible without changing much code at all!

For anyone wanting this functionality, go to map.lua, search for `HBD_PINS_WORLDMAP_SHOW_PARENT` and replace this by `HBD_PINS_WORLDMAP_SHOW_WORLD`. Enjoy ClassicCodex markers on the world map!

(would be really nice to have this as an actual in-game option, though)

**Comment by SwimmingTiger** [comment]
I will consider implementing an option for it. This is really a small change, and there are no performance concerns, because ClassicCodex always draws map markers for the entire world at once.
