### ISSUE TITLE
Small Lags / Frame Drops every 5-6 Seconds

### ISSUE THREAD

**Issue by Spegeli** [project-classic/ClassicCodex#48]
First thx for this wonderfull addon ;-)

But when ClassicCodex is enabled, i got small Frame Drops every 5-6 Seconds.

I play with fixed 60 FPS but every 5-6 Seconds i got a drop down to 30-40 FPS.
It seems that ClassicCodex to a refresh or anything else which cause this frame drops.

This is a known problem which lots of people reports on the curseforge website.

Would be nice if you can add an Option so the User self can set the Time Rate or maybe you can fix this ;-)

**Comment by SwimmingTiger** [comment]
Please try to disable `Nameplate Quest Icon`. This may be the only place in 1.2.2 that will cause sustained performance degradation.

The rendering process has been refactored in 1.2.2 to check the quest log and redraw the map markers only when the quest state changes. Therefore, the nameplate icon is the only place that needs continuous monitoring and may cause the frame drops.

**Comment by pgarneau** [comment]
As @SwimmingTiger said, I can't reproduce frame drops at all with these new changes even in highly saturated zones (like barrens or ungoro)
