### ISSUE TITLE
codex object command not working

### ISSUE THREAD

**Issue by ettern** [project-classic/ClassicCodex#5]
Tried with multiple objects: 
`/codex object Copper Vein`
`/codex object Stolen Supply Sack`

All other commands seems to work

> Message: Interface\AddOns\ClassicCodex\database.lua:271: attempt to index global 'object' (a nil value)
> Time: Sat Aug 10 14:18:22 2019
> Count: 8
> Stack: Interface\AddOns\ClassicCodex\database.lua:271: attempt to index global 'object' (a nil value)
> Interface\AddOns\ClassicCodex\database.lua:271: in function `SearchObjectByName'
> Interface\AddOns\ClassicCodex\command.lua:44: in function `?'
> Interface\FrameXML\ChatFrame.lua:4606: in function `ChatEdit_ParseText'
> Interface\FrameXML\ChatFrame.lua:4267: in function `ChatEdit_SendText'
> Interface\FrameXML\ChatFrame.lua:4303: in function `ChatEdit_OnEnterPressed'
> [string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1
> 
> Locals: self = <table> {
>  SearchVendorByItemName = <function> defined @Interface\AddOns\ClassicCodex\database.lua:364
>  GetRaceMaskById = <function> defined @Interface\AddOns\ClassicCodex\database.lua:101
>  GetBitByRace = <function> defined @Interface\AddOns\ClassicCodex\database.lua:41
>  GetIdByName = <function> defined @Interface\AddOns\ClassicCodex\database.lua:140
>  BrowserSearch = <function> defined @Interface\AddOns\ClassicCodex\database.lua:743
>  SearchItemById = <function> defined @Interface\AddOns\ClassicCodex\database.lua:280
>  SearchQuestById = <function> defined @Interface\AddOns\ClassicCodex\database.lua:386
>  SearchObjectByName = <function> defined @Interface\AddOns\ClassicCodex\database.lua:267
>  GetQuestIds = <function> defined @Interface\AddOns\ClassicCodex\database.lua:673
>  GetIdByPartialId = <function> defined @Interface\AddOns\ClassicCodex\database.lua:161
>  GetBitByClass = <function> defined @Interface\AddOns\ClassicCodex\database.lua:47
>  SearchUnitById = <function> defined @Interface\AddOns\ClassicCodex\database.lua:194
>  SearchUnitByName = <function> defined @Interface\AddOns\ClassicCodex\database.lua:224
>  CompareString = <function> defined @Interface\AddOns\ClassicCodex\database.lua:94
>  SearchQuestByName = <function> defined @Interface\AddOns\ClassicCodex\database.lua:546
>  SearchObjectById = <function> defined @Interface\AddOns\ClassicCodex\database.lua:237
>  lastSearchResults = <table> {
>  }
>  lastSearchQuery = ""
>  FormatQuestText = <function> defined @Interface\AddOns\ClassicCodex\database.lua:661
>  SearchQuests = <function> defined @Interface\AddOns\ClassicCodex\database.lua:559
>  GetBestMap = <function> defined @Interface\AddOns\ClassicCodex\database.lua:179
>  SearchItemByName = <function> defined @Interface\AddOns\ClassicCodex\database.lua:353
> }
> name = "Copper Vein"
> meta = <table> {
>  addon = "CODEX"
> }
> partial = "LOWER"
> search = true
> maps = <table> {
> }
> (for generator) = <function> defined =[C]:-1
> (for state) = <table> {
>  1731 = "Copper Vein"
>  2055 = "Copper Vein"
>  3763 = "Copper Vein"
>  103713 = "Copper Vein"
> }
> (for control) = 1731
> id = 1731
> (*temporary) = nil
> (*temporary) = 1731
> (*temporary) = "Copper Vein"
> (*temporary) = <function> defined =[C]:-1
> (*temporary) = <table> {
>  178045 = "Doodad_OnyziasLairLavaTrapMirror35"
>  180093 = "Contested Banner"
>  153471 = "Food Crate"
>  178046 = "Doodad_OnyziasLairLavaTrapMirror36"
>  180094 = "Contested Banner"
>  92099 = "Cauldron"
>  153472 = "Food Crate"
>  178047 = "Doodad_OnyziasLairLavaTrapMirror37"
>  180095 = "Contested Banner"
>  20979 = "Troll Bonfire"
>  153473 = "Food Crate"
>  22259 = "War Room Chair"
>  180096 = "Contested Banner"
>  61923 = "Wooden Chair"
>  11898 = "Mesa Elevator"
>  24563 = "Highback Chair"
>  12666 = "Twilight Tome"
>  180098 = "Contested Banner"
>  180099 = "Contested Banner"
>  176004 = "Subway Bench"
>  180100 = "Alliance Banner Aura"
>  61924 = "Wooden Chair"
>  176005 = "Subway Bench"
>  180101 = "Horde Banner Aura"
>  176006 = "Subway Bench"
>  180102 = "Neutral Banner Aura"
>  176007 = "Subway Bench"
>  20724 = "Dor'Danil Pillar"
>  20980 = "Troll Bonfire"
>  143242 = "Dwarven Brazier"
>  22260 = "War Room Chair"
>  180104 = "Zandalar Cage"
>  22772 = "Cozy Fire"
>  153482 = "Campfire"
>  143243 = "Dwarven Brazier"
>  24564 = "Highback Chair"
>  25332 = "Danath Trollbane"
>  143244 = "Dwarven Brazier"
>  186250 = "Beer Wagon"
>  143245 =

**Comment by pgarneau** [comment]
Thanks for the report. Commands were added in last minute so didnt get the same amount of testing. Ill look into it

**Comment by pgarneau** [comment]
Tested both of your examples with the latest version and it seems to be working. Also added the `meta` command to check for ores between certain skill levels
