### ISSUE TITLE
Exclamation mark not disappearing

### ISSUE THREAD

**Issue by Fieldy89** [project-classic/ClassicCodex#6]
Is it intended, that the quests which I completed are still marked with an exclamation mark on my minimap? They only disappear after I use /codex clean

**Comment by pgarneau** [comment]
Did you complete them before getting the addon? If so, then its normal for
now until i push a fix. If not, then its a bug.

**Comment by Fieldy89** [comment]
I had the addon before accepting the quest. I just noticed that even after a clean the do reappear after a while. I`m using german language, but on the minimap the quests are in english. Might be a localization issue? Or is it only supposed to work with english client?

**Comment by pgarneau** [comment]
Yeah right now english client is the only one supported for now. The code
should be able to hand languages with a simple change so keep a lookout for
it.

Not home till tomorrow so no changes till then

**Comment by Fieldy89** [comment]
Nice, looking forward to it:) great addon btw!

**Comment by pgarneau** [comment]
@Fieldy89 If you're online, I have a fix setup for the german client, you could give it a try if you're on

**Comment by Fieldy89** [comment]
yep, I can test it

**Comment by pgarneau** [comment]
Add me on discord philippe#0353

**Comment by pgarneau** [comment]
@Fieldy89 I gave you a version with a bad line of code on discord. Newest version should be good and should work for you. Let me know if there's anything
